/**
 * This program efficiently scans a large text file for a specific keyword.
 * By using BufferedReader and the readLine() method, it ensures that only
 * one line of text is stored in memory at a time, preventing memory
 * exhaustion even with files exceeding several hundred megabytes.
 *
 * @author gopal;
 */
package streams;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

public class LargeFileScanner {
    public static void main(String[] args) {
        // Path to the file generated by previous performance demos
        String filePath = "UnbufferedInput.txt";
        String targetWord = "error";
        int matchCount = 0;

        System.out.println("Scanning file for '" + targetWord + "'...");

        // Using try-with-resources to ensure the FileReader and BufferedReader are closed
        try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
            String line;

            // readLine() reads a line of text. A line is considered to be terminated
            // by any one of a line feed ('\n'), a carriage return ('\r'),
            // or a carriage return followed immediately by a line feed.
            while ((line = br.readLine()) != null) {

                // Case-insensitive check: we convert both strings to lowercase
                // to ensure 'Error', 'ERROR', and 'error' are all captured.
                if (line.toLowerCase().contains(targetWord.toLowerCase())) {
                    System.out.println("Match found: " + line);
                    matchCount++;
                }
            }

            System.out.println("\n--- Scan Complete ---");
            System.out.println("Total matches found: " + matchCount);

        } catch (IOException e) {
            // General I/O exception handling if file access is restricted or interrupted
            System.err.println("Error reading the file: " + e.getMessage());
        }
    }
}